# Generated by Django 4.1.1 on 2022-09-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_alter_feed_options_feedcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcomment',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
