# Generated by Django 3.2.15 on 2022-09-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_alter_feedcomment_author_alter_feedcomment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedcomment',
            old_name='feed_id',
            new_name='feed',
        ),
    ]
