# Generated by Django 4.1.1 on 2022-10-05 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9])-([0-9]{3,4})-([0-9]{4})$')], verbose_name='전화번호'),
        ),
    ]
